import dayjs from 'dayjs'
import Head from 'next/head'
import Image from 'next/image'
import relativeTime from 'dayjs/plugin/relativeTime'
import { SignInButton, useUser } from '@clerk/nextjs'

import { api } from '~/utils/api'
import type { RouterOutputs } from '~/utils/api'

dayjs.extend(relativeTime)

const CreatePostWizard = () => {
  const { user } = useUser()

  if (!user) return null

  return (
    <div className="flex w-full gap-x-3">
      <Image
        width={56}
        height={56}
        src={user.profileImageUrl}
        alt={`${user.username}'s profile picture`}
        className="h-14 w-14 rounded-full"
      />
      <input
        type="text"
        placeholder="Type some emojis!"
        className="w-full bg-transparent outline-none"
      />
    </div>
  )
}

type PostViewProps = RouterOutputs['posts']['getAll'][number]

const PostView = (props: PostViewProps): JSX.Element => {
  const { post, author } = props

  return (
    <div key={post.id} className="flex gap-x-3 border-b border-slate-400 p-4">
      <Image
        width={56}
        height={56}
        src={author.profilePicture}
        alt={`${author.username}'s profile picture`}
        className="h-14 w-14 rounded-full"
      />
      <div className="flex flex-col">
        <div className="flex gap-x-1 text-slate-300">
          <span>{`@${author.username}`}</span>
          <span>&bull;</span>
          <span>{dayjs(post.createdAt).fromNow()}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  )
}

export default function Home() {
  const { data, isLoading, isError } = api.posts.getAll.useQuery()

  const user = useUser()

  if (!data || isLoading) {
    return <p>Loading...</p>
  }

  if (isError) {
    return <p>Something went wrong!</p>
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="mx-auto w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {data?.map(({ ...fullPost }) => <PostView key={fullPost.post.id} {...fullPost} />)}
          </div>
        </div>
      </main>
    </>
  )
}
