import Head from 'next/head'
import Link from 'next/link'
import { SignInButton, useUser } from '@clerk/nextjs'

import { api, RouterOutputs } from '~/utils/api'

const CreatePostWizard = () => {
  const { user } = useUser()

  if (!user) return null

  return (
    <div className="flex w-full gap-x-3">
      <img src={user.profileImageUrl} alt="Profile Image" className="h-14 w-14 rounded-full" />
      <input
        type="text"
        placeholder="Type some emojis!"
        className="w-full bg-transparent outline-none"
      />
    </div>
  )
}

type PostViewProps = RouterOutputs['posts']['getAll'][number]

const PostView = (props: PostViewProps): JSX.Element => {
  const { post, author } = props

  return (
    <div key={post.id} className="flex gap-x-3 border-b border-slate-400 p-4">
      <img src={author.profilePicture} alt="Profile Picture" className="h-14 w-14 rounded-full" />
      <div className="flex flex-col">
        <div className="flex text-slate-300">
          <span>{`@${author.username}`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  )
}

export default function Home() {
  const { data, isLoading, isError } = api.posts.getAll.useQuery()

  const user = useUser()

  if (!data || isLoading) {
    return <p>Loading...</p>
  }

  if (isError) {
    return <p>Something went wrong!</p>
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="mx-auto w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {data?.map(({ post, author }) => (
              <PostView
                key={post.id}
                {...{
                  post,
                  author
                }}
              />
            ))}
          </div>
        </div>
      </main>
    </>
  )
}
