import Head from "next/head";
import Link from "next/link";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

export default function Home() {
  const getAll = api.posts.getAll.useQuery()

  const user = useUser()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white text-black">
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton /> }
          <h2>User ID: {user.user?.id}</h2>
        </div>
        <pre>{JSON.stringify(getAll.data, null, 2)}</pre>
      </main>
    </>
  );
}
